version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8083:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8084:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8085:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  contact-mongo-db:
    ports:
      - '27017:27017'
    container_name: contact-mongo-db
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
       MONGO_INITDB_ROOT_USERNAME: nht
       MONGO_INITDB_ROOT_PASSWORD: abc123
       MONGO_INITDB_DATABASE: nht_contact
    image: mongo:6.0-focal
    volumes:
      - ./init_mongo_contact/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: "exit 0"
  unify-mongo-db:
    ports:
      - '27018:27017'
    container_name: unify-mongo-db
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: nht
      MONGO_INITDB_ROOT_PASSWORD: abc123
      MONGO_INITDB_DATABASE: nht_unified_contact
    image: mongo:6.0-focal
    volumes:
      - ./init_mongo_unify/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: "exit 0"
  payment-mysql-db:
    container_name: payment-mysql-db
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'nht'
      MYSQL_PASSWORD: 'abc123'
      MYSQL_ROOT_PASSWORD: 'abc123'
    ports:
      - '3316:3306'
    expose:
      - '3306'
    volumes:
      - ./init_mysql_payment/:/docker-entrypoint-initdb.d
    healthcheck:
      test: "exit 0"
  unify-service:
    image: unify
    depends_on:
      spark-worker-1:
        condition: service_started
      spark-worker-2:
        condition: service_started
      contact-mongo-db:
        condition: service_healthy
      unify-mongo-db:
        condition: service_healthy
      payment-mysql-db:
        condition: service_healthy